### ISSUE TITLE
net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file or a corrupted zip file

### ISSUE THREAD

**Issue by duoluozhe** [srikanth-lingala/zip4j#111]
What's the problem?

```
public static void zipFileWithPassword(List<String> fileList, String zipFileName, String password) {
        try {
            //files
            ArrayList<File> files = new ArrayList<>();
            for (String oneFile : fileList){
                File file = new File(oneFile);
                files.add(file);
            }
            ZipParameters zipParameters = new ZipParameters();
            zipParameters.setEncryptFiles(true);
            zipParameters.setEncryptionMethod(EncryptionMethod.AES);
            zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
            ZipFile zipFile = new ZipFile(zipFileName, password.toCharArray());
            zipFile.addFiles(files, zipParameters);
        } catch (ZipException e) {
            e.printStackTrace();
        }
    }
```
zipFileName 

```
String filename = "/tmp/souquan-net.zip";
File file = new File(filename);
            if (!file.exists()) {
                boolean status = file.createNewFile();
                if (!status) {
                    logger.error("Create zip file error");
                }
            }
```

**Comment by duoluozhe** [comment]
I know the reason , no need new File(), only need new File(path) !

**Comment by srikanth-lingala** [comment]
If you get this exception:

```
net.lingala.zip4j.exception.ZipException: Zip headers not found. Probably not a zip file or a corrupted zip file
```

when you are adding files to a zip, it usually means that a zip file already exists at the specified location, which in your case is `/tmp/souquan-net.zip` and that this zip file is corrupt, and not a valid zip file. When adding files to a zip, zip4j will first check if the zip file already exists. If the file exists, it will try to read the zip headers to add files to the existing zip file. At this step, if the zip file is corrupt, then zip4j will throw the exception you get. If you are adding files to an existing zip file, this zip file has to be a valid zip file.

**Comment by srikanth-lingala** [comment]
To me the problem looks like you are creating a new file if the file does not exist `file.createNewFile()`. This will just create an empty file, which is not a valid zip file. You don't have to create an empty file before calling any of zip4j's addFiles methods

**Comment by duoluozhe** [comment]
Thanks @srikanth-lingala

**Comment by Mudit0027** [comment]
The working code for this along with the password protected zip is :

File dbFile = new File(ctx.getExternalFilesDir("") + File.separator +
                        AppConstants.DB_PATH + File.separator + AppConstants.DB_NAME);
zipName = AppConstants.DB_NAME + "-" + getCurrentDateTime() + ".zip";
ZipFile zipFile = new ZipFile(folderPath + File.separator + zipName);

ZipParameters parameters = new ZipParameters();
parameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
parameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);
parameters.setEncryptFiles(true);
parameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_AES);
parameters.setAesKeyStrength(Zip4jConstants.AES_STRENGTH_256);
parameters.setPassword(AppUtil.decodeStr(AppConstants.DB_PASSWORD));
zipFile.addFile(dbFile, parameters);

However the issue may still appear because of the following reasons:

- Either the source file does not exists while adding to zipFile,
- The app do not have permissions to read the source file,
- The target zip file might consist of special symbols or space in the file name.

**Comment by rohitkumar5058** [comment]
@srikanth-lingala does it open in linux?
