### ISSUE TITLE
version 2.2.6 set password not work for zip

### ISSUE THREAD

**Issue by blackhu** [srikanth-lingala/zip4j#113]
Hi:
My Code:
```
       ZipParameters zipParameters = new ZipParameters();
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.AES);
        zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
        ZipFile zipFile = new ZipFile("/Users/nichu/event_id.zip","password".toCharArray());
        try {
            zipFile.addFolder(new File("/Users/nichu/1212"),zipParameters);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

Desc:
      Create event_id.zip not need password unzip.

**Comment by srikanth-lingala** [comment]
I tried your code and the generated zip file is encrypted has a password. Please check your code if the zip parameters is being overwritten somewhere.

**Comment by enricobasso** [comment]
Same problem here:
```java
ZipParameters zipParameters = new ZipParameters();
    	zipParameters.setEncryptFiles(true);
    	zipParameters.setEncryptionMethod(EncryptionMethod.AES);
    	// Below line is optional. AES 256 is used by default. You can override it to use AES 128. AES 192 is supported only for extracting.
    	zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);

    	List<File> filesToAdd = Arrays.asList(
    	    new File("C:\\Users\\Enrico\\Desktop\\profiles.xml"), 
    	    new File("C:\\Users\\Enrico\\Desktop\\ebasso.id")
    	);

    	ZipFile zipFile = new ZipFile("archive.zip", "password".toCharArray());
    	try {
			zipFile.addFiles(filesToAdd, zipParameters);
		} catch (ZipException e) {
			e.printStackTrace();
		}
```

I tried debugging and the zipParameters are set correctly but after `zipFile.addFiles(...)` is executed the zipFile object has `EncrycptedFiles` set to `false`.

**Comment by srikanth-lingala** [comment]
@enricobasso Do you see the behaviour every time or in some specific situations. I have tested it today and I was not able to reproduce this. And moreover, this is a basic scenario for which there are tests, and none of them fail as well. Do you see this behaviour with older versions as well? (For example 2.2.5?)

**Comment by enricobasso** [comment]
It happens every time (I'm testing your library so I've just a main class with that code). I've tried downgrading to 2.2.5 and below but doesn't change anything.

**Comment by srikanth-lingala** [comment]
It is obvious, but just to be sure, both of them are files, right? And not directories? I mean these two:

```
C:\\Users\\Enrico\\Desktop\\profiles.xml
C:\\Users\\Enrico\\Desktop\\ebasso.id
```

**Comment by srikanth-lingala** [comment]
And to be sure, what do you mean when you say that the password is not set? 

It is possible to view files of an encrypted zip file. Most of the tools (Winzip, 7zip, etc) do not ask for password to view files in an encrypted zip files, because the place where the file information is written is not encrypted. It is only when you want to extract the files, that a password should be required. Do you not have to enter a password to also extract the zip file?

**Comment by enricobasso** [comment]
I'm sorry, I thought that the password was required in order to open the archive. I tried to extract the file and it asked me the password. Sorry if I wasted your time.
I have another question, is it ok that Windows Explorer can't extract files from an encrypted archive createdby zip4j?

**Comment by srikanth-lingala** [comment]
@enricobasso No problem. As I wrote earlier, the location where the file names are stored is not encrypted, which makes it possible to know the name of the files in the zip without the need of a password. However, a password is required to extract the content of an encrypted zip file. It is possible to encrypt also the headers so that even the file names are not readable without the password, however this technique is proprietary, and it is not allowed for 3rd party tools to implement this encryption method.

>  is it ok that Windows Explorer can't extract files from an encrypted archive created by zip4j?

This problem is not just with the zip files generated with zip4j, but you will see the same behaviour with the files generated with 7zip. And it is not just Windows Explorer, but even the default zip tool that comes bundled on a mac has this problem. I noticed this issue a while ago, and looked into it. It seems that these tools (Windows and mac default tools) are not respecting one of the header specification set for an AES encrypted file. As per zip specification, if a zip file is AES encrypted, the compression method written to the headers should be set as "AES" (value 99), and the actual compression method is written in the aes headers. This is as per the zip specification and these tools seem to no respect this specification and throw an error when they see "AES" as the compression method. You can generate a zip file with 7zip (or any similar tool), encrypt it with AES (and not ZipCrypto) and you will see the same behaviour. For a zip file encrypted with ZipStandard, you should not see this behaviour though. So, in short, yes, it is ok that Windows Explorer can't extract these files.
