### ISSUE TITLE
Problem extract single file creates always folder with same name

### ISSUE THREAD

**Issue by stuart1975** [srikanth-lingala/zip4j#115]
Hello,
I have a folder with many zip files and want all in the same folder.
Put currently it looks like it is not possible.

zipFile.extractFile("abc.zip", "C:\\extractedFiles\\"+ "newFileName.txt");
Now it creates an unwanted folder C:\\extractedFiles\\newFileName\\newFileName.txt
with the new file.

Please can you add an option to disable creating unwanted folder.
Thank you.

**Comment by srikanth-lingala** [comment]
The path '\newFileName\newFileName.txt' is added because most likely this is how the file name is defined in the headers. The file name in the headers already has a directory, `newFileName`, and therefore zip4j extracts it with such directory. If I understand your requirement right, you want the possibility to extract all files in the zip file to the root of the directory, in your case to `C:\extractedFiles\`. To achieve this, you have to use `getFileHeader()` and `getInputStream()` to extract the file to the location you want.

You can use the code below to achieve that. I haven't tested the code myself, but hopefully it gives you an idea on how to achieve that.

```
import net.lingala.zip4j.model.FileHeader;
import org.junit.Test;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;

public class ZipTest {

  @Test
  public void extractZipFile() throws IOException {
    ZipFile zipFile = new ZipFile("test.zip");
    String rootDirectoryToExtract = "C:\\extractedFiles\\";

    List<FileHeader> fileHeaders = zipFile.getFileHeaders();
    byte[] buff = new byte[4096];
    int readLen = 0;
    for (FileHeader fileHeader : fileHeaders) {
      String fileName = stripDirectoryNamesFromFileName(fileHeader.getFileName());
      
      try (OutputStream outputStream = new FileOutputStream(new File(rootDirectoryToExtract + fileName));
           InputStream inputStream = zipFile.getInputStream(fileHeader)) {
        
        while ((readLen = inputStream.read(buff)) != -1) {
          outputStream.write(buff, 0, readLen);
        }
      }
    }
  }

  private String stripDirectoryNamesFromFileName(String fileName) {
    if (!fileName.contains("/")) {
      return fileName;
    }

    return fileName.substring(fileName.lastIndexOf("/") + 1, fileName.length());
  }
}
```
