### ISSUE TITLE
FileHeader fileName encode with gbk has wrong char(zip4j2.2.8)

### ISSUE THREAD

**Issue by tustar** [srikanth-lingala/zip4j#122]
1. I used zip4j encode FileHeader fileName with GBK has wrong char.
2. The reason is byte[] -> UTF-8 string -> GBK string， UTF-8 string getBytes("UTF-8") is not same to old byte[]
2. I had fixed it by override the HeaderUtil.java decodeStringWithCharset.

```
  /**
   * Override the zip4j decodeStringWithCharset method
   *
   * @param data
   * @param isUtf8Encoded
   * @param charset
   * @return
   */
  public static String decodeStringWithCharset(byte[] data, boolean isUtf8Encoded, Charset charset) {
    if (isUtf8Encoded) {
      return new String(data, InternalZipConstants.CHARSET_UTF_8);
    }

    if(charset != null) {
      return new String(data, charset);
    }

    try {
      return new String(data, ZIP_STANDARD_CHARSET);
    } catch (UnsupportedEncodingException e) {
      return new String(data);
    }
  }
```

**Comment by srikanth-lingala** [comment]
Can you please attach a sample zip file where you see this issue? Unfortunately, I did not the issue you are facing. I am not sure if the override you did is the right fix for an issue. Because the charset provided by the user should get more priority than utf8, and therefore this if condition:

```
if(charset != null) {
  return new String(data, charset);
}
```
should come before:

```
if (isUtf8Encoded) {
  return new String(data, InternalZipConstants.CHARSET_UTF_8);
}
```
And moreover, there are [some tests][1] with GBK charset as well and they successfully read the file names as expected.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/test/java/net/lingala/zip4j/ExtractZipFileIT.java#L309

**Comment by srikanth-lingala** [comment]
Closing the issue as there is no further feedback. Feel free to reopen if you have any further feedback.
