### ISSUE TITLE
compressed encrypted zip file, not supported on Mac

### ISSUE THREAD

**Issue by lisw1993** [srikanth-lingala/zip4j#126]
![image](https://user-images.githubusercontent.com/47241572/72038466-6e1fe780-32dc-11ea-97b6-92db281073d6.png)

ZipFile zipFile = new ZipFile(getWritePath(filePath, zipFileName), password.toCharArray());

        for (Entry entry : entries) {
            ZipParameters zipParameters = new ZipParameters();
            zipParameters.setEncryptFiles(true);
            zipParameters.setEncryptionMethod(EncryptionMethod.AES);
            // Below line is optional. AES 256 is used by default. You can override it to use AES 128. AES 192 is supported only for extracting.
            zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);

            zipParameters.setFileNameInZip(entry.getFileName());
            zipFile.addStream(entry.getInputStream(), zipParameters);
        }

**Comment by srikanth-lingala** [comment]
This is a known issue, and I have mentioned about it in some issues previous raised here, but unfortunately I can't seem to find where I wrote about it. 

The inbuilt zip tool in mac does not seem to follow the AES specification. To explain this issue I have to explain briefly about the zip specification. AES zip specification mentions that when an entry is encrypted using AES, the compression method has to be set to 99 and the actual compression method is then defined in the aes header. A lot of tools out there respect this specification, and so does zip4j. zip4j writes the actual compression method in aes headers. But the zip tool that comes bundles with mac seem to not follow that specification. As soon as it sees the value 99, it throws an error that the compression method is unknown. Unfortunately, there is nothing much zip4j can do here. As mentioned earlier, the issue is with the zip tool that comes bundled with mac and that needs to be fixed.
