### ISSUE TITLE
The size of the split files differs from the set value

### ISSUE THREAD

**Issue by sinakma** [srikanth-lingala/zip4j#130]
Thank you for providing such a good library.
I've been using your library since version 1.x and I'm using it to create split zip files with encryption.
While testing 2.3.0 version, I got an unexpected results with regards to 'split length'.
For example, when I input 524288000L (500MiB) to the split length, the expected file size was 512,000 KB, but some files had values like 511,998 KB instead of the set values.
I wonder if this is the intended result.

**Comment by srikanth-lingala** [comment]
There will be some variation in the size of the generated file. It can be due to different reasons: one is that the file header information is not allowed to be split between files, it means that if some file header is being written exactly at the split length and it has to be spread over two files, then the complete header information has to be written at the beginning of the second split file. Second reason can be that write buffer before writing the current block checks to see if the length would go over the limit if the current block is written. If yes, it just continues writing the complete block from the second split file. 

But in any case, the length of the split file will (and should) never go over the split limit. It can be slightly less than the limit (a couple of kb at most), but never over the limit.
