### ISSUE TITLE
Filenames not correctly encoded when compressing ZIP

### ISSUE THREAD

**Issue by suushiemaniac** [srikanth-lingala/zip4j#131]
# Expected behaviour

When creating a ZIP file with a file name that includes non-ASCII characters, the file header gets encoded correctly so that unpacking the ZIP yields readable output

# Actual behaviour

The file name in the ZIP headers are gibberish, and my native ZIP viewer (Manjaro 18.1.5) displays any non-ASCII symbols as question marks

# Version info

Zip4j version 2.3.0
Java version 11.0.5
Kotlin version 1.3.61

# Reproduction example (written in Kotlin)

```kotlin
val baosZip = ByteArrayOutputStream()
val zipOut = ZipOutputStream(baosZip, ENCODING_CHARSET)

val zipParams = ZipParameters().apply {
    compressionMethod = CompressionMethod.DEFLATE
    compressionLevel = CompressionLevel.NORMAL
    fileNameInZip = "åscîi.txt"
}

zipOut.putNextEntry(zipParams)
zipOut.write("Hellø, Wørld!".toByteArray())
zipOut.closeEntry()

zipOut.close()

val zipContents = baosZip.toByteArray()
File("/tmp/path/to/file.zip").writeBytes(zipContents)
```

then inspecting the resulting file yields:

```bash
$ zipinfo /tmp/path/to/file.zip
Archive:  file.zip
Zip file size: 153 bytes, number of entries: 1
-rw----     2.0 fat       15 bl defN 20-Jan-20 11:41 +Ñsc+«i.txt
1 file, 15 bytes uncompressed, 17 bytes compressed:  -13.3%
```

# Possible fixes

Interestingly, packing the ZIP works just fine when passing an additional `IBM437` encoding (Java title for `cp437`) parameter to the `ZipOutputStream` like so:

`ZipOutputStream(baosZip, ENCODING_CHARSET, Charset.forName("IBM437"))

resulting in the following (correct!) zipinfo:

```bash
$ zipinfo /tmp/path/to/file.zip 
Archive:  file.zip
Zip file size: 149 bytes, number of entries: 1
-rw----     2.0 fat       15 bl defN 20-Jan-20 11:49 åscîi.txt
1 file, 15 bytes uncompressed, 17 bytes compressed:  -13.3%
```

However, the ZIP archive viewer still shows the filename as corrupt `?` symbol instead of `å`, leading me to suspect that some header information is not correctly being passed along.

**Comment by suushiemaniac** [comment]
Update: I found a way that produces correct ZIPs (i.e. files that are readable by my OS's ZIP reader). But I have to go to encoding hell in order to get there and that doesn't seem healthy at all:

Here's what I do for any given `filename`:
1. Get the `UTF-8` bytes of `filename`
2. Create an `ISO-8859-1` string out of those bytes
3. Have the `ZipOutputStream` use an `IBM850` (synonym for `Cp850`) encoding to write the ISO-converted UTF-bytes into the header

This seems *extremely* hacky but it yields the desired result in the end. I will be more than happy to share details in an effort to fixing this problem, but I don't know that much about ZIP to be able to estimate what to share exactly

**Comment by suushiemaniac** [comment]
More updates: The "fix" described above apparently works for å and î but not for Polish ł

Please advise on how to debug ZIP headers properly, and what encoding should be dumped into them in the first place.

**Comment by srikanth-lingala** [comment]
Thank you for the detailed issue. I highly appreciate when someone provides all the details of the issue in such way as you did. It makes it much easier for me to investigate.

Zip4j uses the standard defined in zip specification to handle these non-ascii characters. I will explain it briefly here, but will not bore you with too many details. Zip specification specifies to use `Cp437` for Ascii characters, and utf8 for non-Ascii characters. Zip4j, by default uses utf8 when creating zip files (even for ascii characters). This reduces complexity of determining wether file name is ascii/non-ascii and makes zip4j still zip standard compliant. This charset flag (of wether it is a Cp437 or utf8) is stored as a boolean (0 or 1) in zip headers. 0 means Cp437 and 1 means utf8. Zip4j has additional feature for user to pass in custom charset as well. Applications should then use the same charset to extract the file, as there is no way for zip to store custom charset information. If custom charsets are used, the zip file is not interoperable with other zip tools, and only tools which can take in custom charsets can decode the file name correctly.

Now back to the issue you mentioned, I see in your code on line:

`val zipOut = ZipOutputStream(baosZip, ENCODING_CHARSET)`

that you use `ENCODING_CHARSET`. What charset are you using here? What is the outcome when you do not use any custom charset? Because, as mentioned earlier, zip4j uses utf8 by default and the characters you mentioned should be supported by default by zip4j without you have to use custom charsets. I just tried the java version of your example without any custom charset, and it works fine.

```
ZipOutputStream zipOutputStream = new ZipOutputStream(new FileOutputStream(new File( "sample.zip")));
ZipParameters zipParameters = new ZipParameters();
zipParameters.setFileNameInZip("åscîi.txt");

zipOutputStream.putNextEntry(zipParameters);
zipOutputStream.write("Hellø, Wørld!".getBytes());
zipOutputStream.closeEntry();
zipOutputStream.close();
```

**Comment by suushiemaniac** [comment]
Thank you for the reply, I equally appreciate your insight into the ZIP standard! To answer your question, `ENCODING_CHARSET` was intentionally undefined as a placeholder for "whatever charset you wish to use in your experiments", I should have been more clear about that. Sorry :(

I have tried your minimal Java example, and I run into the same issue as in my original post. However, your insights have led me to suspect my ZIP reader as a problem, and as a result I tried out a couple more alternatives.
Turns out, some of them display the same exact ZIP file correctly, and some of them don't. In particular, I am astonished that the default Linux `xarchiver` does not recognise the default `UTF-8` encoding…

I will attach both versions to this issue, one "vanilla" with your solution of using `2.3.0` without any additional encoding settings at all, and one with my "triple encoding" hack. Maybe this will help you debug. Have you considered creating a "string diff" between user input and NKD-normalised strings to figure out which characters are ASCII and which ones aren't?

In terms of the actual _solution_ to my problem, I think it will be best to rethink our ZIP packaging and use IDs that only contain ASCII symbols by definition. I see that it requires far too much work to get `åscîi` to work properly.

Just as a final brain teaser, I can assure you my "triple encoding" hack only works when specifying `Cp850` encoding, but I also have absolute confidence in your explanation that ZIP uses `Cp437`. That may be a tough nut to crack, if you want to crack it at all :P

[VANILLA.zip](https://github.com/srikanth-lingala/zip4j/files/4107754/i18n-java.zip)
[TRIPLE-ENCODING.zip](https://github.com/srikanth-lingala/zip4j/files/4107761/i18n-java.zip)

**Comment by srikanth-lingala** [comment]
In Vanilla.zip attachment, I see this as a file name: `åscîi.txt` which I presume is as expected. 

> Have you considered creating a "string diff" between user input and NKD-normalised strings to figure out which characters are ASCII and which ones aren't?

zip4j 1.x used to do this. I only remember now that this lead to some complexities and issues, although I don't quite remember the details. And hence the decision to use utf8 for all. To use utf8 is in no way violating zip standard. Zip allows to use utf8 as a charset. So, I felt the risk was not worth to determine Ascii/non-ascii and to use utf8 all the time. And honestly speaking I haven't heard of any issues since then, especially considering the fact that zip4j is being used across all parts of the globe.

My goal with zip4j is to stick with zip specification to as much extent as possible. I think the issue you have mentioned is an issue with the tools that are reading the zip file. I am equally surprised as you that default linux archiver does not recognise utf8 charset. But I am not too much surprised as well, because there is at least one known bug with the archiver that comes bundled with mac, which also deviates from the standard spec.

To wrap up, my conclusion would be that this is an issue with the tools reading zip file and not an issue with zip4j.
