### ISSUE TITLE
File containing Path traversal payload is unchecked

### ISSUE THREAD

**Issue by punitnagar** [srikanth-lingala/zip4j#133]
Team- we found an issue where a file containing a path traversal payload is not validated before unzipping the file. Take a zip file that contains the path traversal payload in the name (../) and try to unzip the file. After a call to the extractAll API (zipFile.extractAll(destimation_path), the file isnt unarchived at the destination location but at the root location.

is there a fix available for this vulnerability?

**Comment by srikanth-lingala** [comment]
Yes, I was able to reproduce this. There is [a check in zip4j][1] to avoid such issues, but it currently only checks if the path is completely different than the extraction path. If it is a parent path, this check will go through. Will fix it.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L42

**Comment by srikanth-lingala** [comment]
Actually, I will modify my earlier comment. The linked code in the above comment is there to exactly prevent these issues. And in my further tests, zip4j throws an exception when the path is something other than path being extracted to, even if it is a parent path. 

For example, the following code will fail with an exception (which is as expected):

```
ZipFile zipFile = new ZipFile(BASE_DIR + "sample.zip", "password".toCharArray());
ZipParameters zipParameters = new ZipParameters();
zipParameters.setFileNameInZip("../somename.pdf");
zipFile.addFile(new File(BASE_DIR + "fileToAdd.pdf"), zipParameters);

zipFile.extractAll(BASE_DIR + "test/extracted/");
```

However, I was able to reproduce the issue when the file name in zip has the same name as the directory being extracted to. For example the below code goes through without any exception, and the file is extracted not to `some` but to `test` directory.

```
ZipFile zipFile = new ZipFile(BASE_DIR + "sample.zip", "password".toCharArray());
ZipParameters zipParameters = new ZipParameters();
zipParameters.setFileNameInZip("../somename.pdf");
zipFile.addFile(new File(BASE_DIR + "fileToAdd.pdf"), zipParameters);

zipFile.extractAll(BASE_DIR + "test/some/");
```

The difference is that extraction path in the first example has `extracted` in the name whereas in the second example it is `some`, and this text begins with the file name `somename.pdf` which is written to the zip file. This is a very interesting find, because most of the documentation out there of how to handle such situations will also fail in such scenarios. Is it also the case in your code that the file name has the first characters same as the directory name being extracted to?  I will work on a fix, although I guess it might be a slightly tricky one.

BTW, all this is only applicable in zip4j v2.x (and preferrably the latest version). zip4j 1.x does not have this fix. This issue is also called `zip slip`.

**Comment by srikanth-lingala** [comment]
I managed to find a simple fix for it. Issue is fixed. Will include it in the next release.

However, I would highly recommend you to read through the comment above to see if your circumstances were same to the circumstance I was able to reproduce the issue with.

**Comment by attaullahpro** [comment]
https://github.com/snyk/zip-slip-vulnerability, I think the issue is resolved v1.3.3 according to zip-slip-vulnerability

**Comment by srikanth-lingala** [comment]
@attaullahpro Yes, this was originally fixed as part of zip slip fix in v1.3.3. But there were a few more enhancements in the fix in v2.x.

**Comment by srikanth-lingala** [comment]
Fixed in v2.3.1 released today.

**Comment by punitnagar** [comment]
Srikanth- I tested the new version released and still see the path traversal vulnerability in there. The below file will give off the vulnerability.
[Archive(1).zip](https://github.com/srikanth-lingala/zip4j/files/4245494/Archive.1.zip)

**Comment by srikanth-lingala** [comment]
I get the following exception when I test with your sample zip file

> net.lingala.zip4j.exception.ZipException: illegal file name that breaks out of the target directory: ../../../files/Logs/RollingLogs.txt

Below is the code I used:

  ```
  @Test
  public void testExtractZipFile() throws IOException {
    ZipFile zipFile = new ZipFile(BASE_DIR + "/test/1/Archive.1.zip");
    zipFile.extractAll(BASE_DIR + "test/1/");
  }
```

**Comment by srikanth-lingala** [comment]
and the value of `BASE_DIR` was `/Users/srikanth/Downloads/`
