### ISSUE TITLE
Help with extracting

### ISSUE THREAD

**Issue by Crack3dC0d3** [srikanth-lingala/zip4j#138]
So im using your lib (Its awesome!) But i cant figure out how to delete the file after the extracting is done. I mean i can delete the file but some of them are still processing and cannot be deleted. Is there a way to do this?

**Comment by srikanth-lingala** [comment]
Can you please share your code and some more details like the OS, java version, etc? After the extraction is done, zip4j should release all file handles, and therefore it should be possible to delete the file. Can you also please make sure that no other part of your application is accessing this file? There was a similar issue reported a few months back, but it turned out that another part of the application was still accessing the file and therefore it was not possible to delete the file.

**Comment by srikanth-lingala** [comment]
I tested it and the zip file gets successfully deleted. When running asnyc, you have to make sure that you wait until zip4j extraction process is complete. I tested with the code below:

```
@Test
public void testGenerateZipFile() throws IOException {
  ZipFile zipFile = new ZipFile(BASE_DIR + "sample.zip");
  zipFile.setRunInThread(true);
  zipFile.extractAll(BASE_DIR + "test/");

  ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
  while (progressMonitor.getState() == ProgressMonitor.State.BUSY) {
    System.out.println("Extracting. Percent done: " + progressMonitor.getPercentDone());
  }
  System.out.println("Extraction complete. Result: " + progressMonitor.getResult());
  Assert.assertTrue(zipFile.getFile().delete());
}
```

**Comment by srikanth-lingala** [comment]
I hope the example above helped. I am closing this issue now. Reopen if it still does not work for you.
