### ISSUE TITLE
Can't currently rename all files in zip using addFiles

### ISSUE THREAD

**Issue by dayglorious** [srikanth-lingala/zip4j#145]
Hi again. I have a couple instances where I am creating an archive with multiple files that need to be renamed -- for instance, from a UUID to a user-friendly file name or vice versa. I'm not seeing any way to do that with addFiles(), and looping through an array of files to add each one individually with addFile() means that the information returned by progressMonitor only reflects the progress for each individual file, not the group of files as a whole. In the source for AbstractAddFileToZipTask.addFilesToZip(), I can see that the ZipParameters are changed every time a new file is added, so at least in theory, a new name could be set for each file before it is added.  But since that function takes a list of file objects, with no way to specify ZipParameters for each individual file, there's currently no way to make that happen.

**Comment by srikanth-lingala** [comment]
There is a [feature request open][1] to rename files. I think that is what you are looking for. I haven't gotten around to implementing this feature yet because of lack of time, but hopefully I can get it done in the next few days. But it is good to have ready your use case, I can implement this feature to take in a list of entries to be changed, and not only just one entry.

[1]: https://github.com/srikanth-lingala/zip4j/issues/72

**Comment by dayglorious** [comment]
Sorry for the delayed response. That's not quite what I was looking for.  I'm not looking to rename files in a zip after they have already been added. I'm looking to add them to the zip with new names. When adding a single file, I can use setFileNameInZip() on a zipParameters object that I pass in the arguments. (Note: I had to add a function to get the zipParameters from zipFile in order to make that happen.) There's currently no way to do that for multiple files.

**Comment by srikanth-lingala** [comment]
Ok. I get your requirement. It will be slightly hard to come with a solution for this. Because that would mean taking in a Map or something equivalent with the mappings of the original file names and the file names to be changed to. I will spend some thoughts if a solution for this is possible, although at the moment, it seems difficult. I also have to consider how often such a feature will be used. A workaround would still be to rename the files in the zip after they have been added, although I agree that it takes some slight overhead of changing the zip file again, but as I said earlier, an easy solution to this, without drastically changing the api, seems a little difficult at the moment. If you have any ideas, I would be happy to hear them.

**Comment by srikanth-lingala** [comment]
To be honest, this is really a unique request to be able to rename files when being added to a zip or when creating a zip file. The parameter `fileNameInZip` of `ZipParameters` is supposed to be used when working with streams. (Ideally, there should have been different objects for streams and ZipFile api, but for historical reasons they are the same).  This can also come in handy when adding a single file. But it is not meant to be used for multiple files. 

You can achieve that by renaming the entries after they have been added. I have implemented the feature request #72 , by which it will now be able to rename entries in a zip, and you can also rename multiple files at once. Please note that the feature is not yet released, but I plan to release it in a few hours from now.

I will close this issue for the reasons mentioned above.

**Comment by dayglorious** [comment]
Renaming files after they are added will not work when files with the same name from different source folders are involved -- a scenario I deal with often.
