### ISSUE TITLE
Preserve Directory structure in addFiles

### ISSUE THREAD

**Issue by marcuslamb** [srikanth-lingala/zip4j#153]
Given a List<String> of files added to a zip using addFiles(), would it be possible to preserve the original directory structure of those files.

Specifically I have the following situation:

I have a method - List<String> generateFileList(...) that essentially takes a parent directory and then matches all files in that and any subdirs based on a regex and returns a list of all relative path names for files that match.

When I add this files using ZipFile.addFiles(...), it puts everything in a flat structure with none of the directories.

I'm not sure if keeping the directories is currently possible in zip4j or if something needs to be added  - maybe an addition to ZipParameters ?

**Comment by srikanth-lingala** [comment]
This feature brings a few questions/concerns that need to be addressed before considering adding this as a new feature in zip4j. Most of the concerns are not when adding the files, but when extracting, and especially interoperability.

- How is a file in a zip that is preserved with complete path supposed to be extracted when being extracted on a different os than the current os being extracted on. For example, imagine a file on Windows in location `E:\some_dir\some_file.txt`. If this path is preserved as-is, extracting this entry on linux or mac will lead to some issues. Even on Windows, if the host OS does not have a drive `E:`, this will also cause some issues. Even if I truncate the Windows drive letter, it still leads to issues, especially restoring it to the original location, as mentioned in the next point. 

- How is zip4j (or any other zip tool) supposed to know which path has to be restored to the original directory location and which needs to be created under the current extraction directory? For example, lets say that a file on mac under the location `/Users/some_user/some_dir/some_text.txt` is added to a zip file and that complete path is stored in the file name, it will not be easy to determine to restore this to the original location (under the Users os directory) or if this file has to be extracted as a directory under the directory being extracted to. Even if some parameter is passed to zip4j, this will not be compatible with other tools, and moreover, I am not completely sure, if a file name in zip can start with  root directory of the OS ("/" in linux/mac and drive letter on Windows).

- Currently `ZipFile.extractAll(String)` takes a `String` parameter which is a extraction path. What value should be passed in this case? If under linux/mac it is `/`, what should be the value under Windows/Android? An empty string cannot work, because what if some entries do not have complete path? 

- This is not part of the zip specification, so it will break interoperability between zip tools and OS

I think that this feature is very specific to the machine that is being worked on. That is, the zip file being created can only be extracted on that particular machine. 

A workaround I can suggest is to use the `ZipParameters.rootFolderNameInZip`. For example, if you want to add the following files to zip: `/Users/some_user/some_file.txt`, `/var/logs/logfile.log`, `/etc/some_dir/some_config.txt`, you have to set the `rootFolderNameInZip` to complete parent path excluding the `/`. In the first case, this will be `Users/some_user/`, and for second file it will be `var/logs/`, and so on. And when you use `ZipFile.extractAll()` pass in the root dir, which on mac/linux will be `/`. This workaround works better on Linux/Mac than on Windows; the limitation on Windows being that the files cannot span multiple drives. If they are all on the same drive, you can pass in `ZipFile.extractAll("C:\\")`. I haven't tested this workaround though.

**Comment by joorei** [comment]
@marcuslamb Maybe the confusion is on my part, but do you possibly want the following files in your filesystem
```
my_folder/file_a.txt
my_folder/fiel_b.txt
my_folder/subfolder_c/subfolder_d/file_e.txt
```
not result in three corresponding FileHeaders (ZIP entries) but the following FileHeaders instead?
```
my_folder/
my_folder/file_a.txt
my_folder/fiel_b.txt
my_folder/subfolder_c/
my_folder/subfolder_c/subfolder_d/
my_folder/subfolder_c/subfolder_d/file_e.txt
```

**Comment by marcuslamb** [comment]
Hi @srikanth-lingala - Thanks for the quick response. I think I might not have been clear with my original question and also me not fully understanding zip4js model.

I think @joorei has it right. It's not the complete path I wish to preserve, only the path relative to parent directory. Essentially I have a list of files that share a common root and I want to add them from that root while keeping their relative path.

As you pointed out in your first response I can to this by using `rootFolderNameInZip` for each of the entries, it just means I have to iterate over my file list and add them individually. 

I have tested this on Linux and Windows and it works the way I need it to. Thanks again.

**Comment by srikanth-lingala** [comment]
@marcuslamb I definitely misunderstood your requirement. But good to know that you got it working. I will now close the issue.
