### ISSUE TITLE
Bug: using ZipInputStream, unable to get entry file size

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [srikanth-lingala/zip4j#168]
Just like we have ZipInputStream ZipeEntry of "size" function:
https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipEntry.html#getSize()
https://developer.android.com/reference/java/util/zip/ZipEntry#getSize()

I'm trying to do the same, but it fails on the library to get the size:

    implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.5.1'

```kt
        thread {
            try {
                val file = File("/storage/emulated/0/test.zip")
                ZipInputStream(FileInputStream(file)).use {
                    while(true){
                        val entry: LocalFileHeader = it.nextEntry?:break
                        Log.d("AppLog", "entry:${entry.fileName} ${entry.uncompressedSize} ${entry.compressedSize}")
                    }
                }
                Log.d("AppLog", "got archive ")
            } catch (e: Exception) {
                Log.d("AppLog", "Error:$e")
                e.printStackTrace()
            }
        }
```

![image](https://user-images.githubusercontent.com/5357526/78049374-aa1a9400-7383-11ea-904c-6e432a2e270c.png)

Attached sample Android project and ZIP file that it fails to get its entry size:

[ZipTest.zip](https://github.com/srikanth-lingala/zip4j/files/4410256/ZipTest.zip)

[test.zip](https://github.com/srikanth-lingala/zip4j/files/4410257/test.zip)

**Comment by srikanth-lingala** [comment]
I wonder which tool you used to generate the zip file. There is something wrong with the way the zip file was generated. To explain that I have to explain a bit about zip concepts. Preceding every entry in a zip file is a file header which contains the compressed and uncompressed sizes. In some cases, when creating zip files, if the tool which is generating a zip file, cannot seek the stream that it is writing to, the compressed and uncompressed sizes are written after the entry, and these sizes are stored as 0's in the location preceeding the entry. But if the file in the zip is stored using compression method "STORE", then the tool is supposed to write the compressed and uncompressed sizes in the location preceeding the entry. That is because the tool knows upfront both these values and can write them when writing the headers preceeding the entry in the zip, whereas when an entry is being added using "DEFLATE" compression, a zip tool cannot know the compressed size upfront and therefore writes it in a block after the entry (this block is called Data Descriptor). Note that this behaviour is usually done (but not exclusively) when the tool cannot seek through the stream that it is writing to, for example, when writing with an OutputStream instead of a RandomAccessFile. 

There are two aspects to your question. 

1) when the entry is stored using "STORE" compression method, which is the case in your zip file. In this case, there should have been compressed and uncompressed sizes written to the header preceeding the entry, but this was not the case, and therefore the tool which generated the zip file did not create it the right way

2) If it was the case that the entry was with "DEFLATE" compression, then these values will be zeros, as even zip4j does not have access to this information upfront, and only has access to this information after the complete entry is read through. (Again, this is only the case if Data Descriptor is present)

### **But, there is a work-around for your use case.** 

And since your are working with files, it is probably even a preferred approach (unless have reasons not to). Instead of using `ZipInputStream`, you can use `ZipFile` api from zip4j. In this case, your code will be something like:

```
ZipFile zipFile = new ZipFile(file);
List<FileHeader> fileHeaders = zipFile.getFileHeaders();
fileHeaders.stream().forEach(e -> System.out.println(e.getCompressedSize()));
```
`ZipFile` behaves differently than `ZipInputStream` and it has access to the information you need (in case of your zip file) , which is a bit restricted when using `ZipInputStream`

**Comment by AndroidDeveloperLB** [comment]
It is an issue. I can't use ZipFile. I want to use it on Android, with streams, because not all zip files are stored on the file system or are easily reachable.
Google plans to ruin storage permission on Android R, so people will have to use InputStream (created whenever you wish, from a Uri)  instead of file-path.

I used a file to demonstrate it easily. I want to use ZipInputStream (and of course, avoid copying it to a real file and then use ZipFile).

As for how I got this, I've noticed APK-mirror website creates its own format of split-APK files (APKM) which is very closed sourced ([here](https://github.com/android-police/apkmirror-public/issues/119)), so I've found another popular website that allows people to download split APK files from. Its file format ([xapk](xapk)) is a simple zip file, and this one is a sample from there, after I've removed some files inside (using [7-zip tool](https://www.7-zip.org/) on the PC)

Please fix this issue.
Why do you mark it as "not an issue" ? The library is supposed to handle zip files well, and it failed to handle one...
I'm sure every zip file there would cause the same issue.

**Comment by srikanth-lingala** [comment]
> The library is supposed to handle zip files well, and it failed to handle one...

I disagree that zip4j failed to handle this zip file. This zip file that you have attached is not generated in a way that follows the standard when a zip file has data descriptor. Not only zip4j, but any library/tool out there cannot get you the information you are looking for (in your zip file) as long as you are using streams because this information is not yet available when working with streams, for the reason mentioned above. 

Again, the entry in your zip file is written using STORE compression method. And in this case, even when using data descriptor (look above for what data descriptor is or refer to zip specification), the tool which generated the zip file is supposed to write compressed and uncompressed sizes in the entry header preceeding the zip file, which it did not. And there is no way that zip4j (or for that matter any other library) can have access to this information when using InputStream. And for this reason, I have marked this as "not an issue", because, it is not an issue with zip4j, but it is an issue with the tool that generated the zip file.

**Comment by AndroidDeveloperLB** [comment]
So what can I do for example, if such a zip file is inside another zip file?
The workaround you mentioned can't work.
You would have to extract the content into real files.

I don't understand how come it's impossible to get the sizes of inside. How come ZipFile can do it, and ZipInputStream can't?
Does ZipFile read the entire content ?

Isn't there any workaround possible when the input you have is InputStream (without using ZipFile) ?

**Comment by srikanth-lingala** [comment]
> How come ZipFile can do it, and ZipInputStream can't?

`ZipFile` does not work with streams, it works with RandomAccessFile, which allows it to seek to any position in the file and get the information it needs. You will not have this flexibility when working with streams. In a zip file, entry sizes are located before the header and in zip "metadata" (called central directory in zip terminology) at the end of the file. ZipFile reads the data it needs from this metadata.

> Suppose I can create the InputStream whenever you wish (and I can because it's from a Uri). Could it be a good thing to help you get the file size inside ?

No. This won't help either. 

> Isn't there any workaround possible when the input you have is InputStream (without using ZipFile) ?

Unfortunately no. As mentioned several times in my comments above, the zip file was wrongly generated. 

Don't get me wrong, in most of the zip files, it is possible to get the entry sizes even when working with streams, especially when the entries in zip file does not have data descriptors. You can for example check if the data descriptor exists, and for those files you can declare them "unsupported" in your use case. You can check for data descriptor from local file header with `LocalFileHeader.isDataDescriptorExists()`.  But in the sample zip file that you have attached, it is not possible to get the information you need from streams.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. In both ways you get access to the entire content of the file. In both of them you can see every tiny bit of information you need.
Using a stream, you can skip to any position, and if you need to go back to the beginning, you can create a new stream again.

**Comment by srikanth-lingala** [comment]
Reading the whole content into the memory and trying to find the information you need might be extremely inefficient. As I have said many times earlier in this issue, the zip file is wrongly generated. And there is no way that I can now include something in zip4j for a zip file which is basically corrupt and does not follow zip standards. If you want to go ahead do it anyway, you will need a custom built solution, and for that I recommend you go through zip specification and/or zip4j source code to understand how to read headers, and then implement your own solution to extract the information you need. I am going to close this issue now.

**Comment by AndroidDeveloperLB** [comment]
Wrongly generated doesn't mean it shouldn't be possible to read it at all using inputStream, because ZipFile succeeds.
Using Apache's solution, the all-in-mem solution worked, but for more efficient solution it would take much more work.

**Comment by srikanth-lingala** [comment]
> Wrongly generated doesn't mean it shouldn't be possible to read it at all using inputStream

Zip4j already can take care of some of such corrupt zip files. But it was done because they were possible to do, and without thinking about any performance impact. What you are asking to do is to read the complete content into a byte array, and loop over it several times (because we are dealing via inputstream) until the desired data is extracted. This can be extremely ineffecient, and if it was a generic feature of zip, I would have considered integrating into zip4j, but going through all that for a corrupt zip file is something that I cannot consider. And that too, what you want to achieve is possible already in current version to get from ZipFile api, but will not be possible when reading with streams.

> because ZipFile succeeds and I can open the file using various apps, including on PC.

You still don't seem to get what I am trying to suggest. ZipFile of zip4j and other tools read the zip metadata which is at the end of the file to extract the content metadata. This cannot be done with an InputStream for the zip file you have provided. The only way to get this from an inputstream is to read the content backwards, which is an extremely in-effecient way to read from an inputstream, because you have to close and open the stream at the desired position several times.

Anyway, I am glad you got it working with Apache library.

**Comment by AndroidDeveloperLB** [comment]
I didn't say the solution is to read all into memory. I said it's a possible thing to do.
Here's what I think could be done:
Read only what's needed, cache things that should be used later. Ignore content of the zip itself. To get the content later, it's possible to re-create the stream again. The new situation of Android is that storage permission got restricted, so what you get is a Uri to something (could be a file, could be something else), but you can re-create the InputStream of it whenever you wish.

So, another possible solution that doesn't need so much memory and/or storage could be of 2 steps:
1. Get only the entries meta-data : name, size, and a some pointer-like variable to reach its data (and other stuff if needed). This can be done by caching what's needed on the way while reading from the InputStream.
2. When we want to read from the entry (get its stream), use a new InputStream from the Uri and the data that we got on the previous step.
