### ISSUE TITLE
how to unzip split file on linux?

### ISSUE THREAD

**Issue by yarix** [srikanth-lingala/zip4j#180]
1. Thanks for the tool, very useful !!, i've created a split zip file with it (log.zip, log.z01, log.z02 etc.)

2. wheh i try to unzip it in linux i get errors like 
```
# unzip log.zip
Archive:  log.zip
warning [log.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
```
3. when workaround it with `cat` it seems to work but it still get errors and warnings 
```
# cat log.z* > aa.zip
# unzip aa.zip
Archive:  aa.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [aa.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
warning [aa.zip]:  1310720000 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  1310720004
  (attempting to re-compensate)
[aa.zip] data.csv password:
  inflating: data.csv
```

what is the recommended way to unzip a split zip?

**Comment by srikanth-lingala** [comment]
As the warning message says `Expect "errors" and warnings...true multi-part support doesn't exist yet (coming soon).`, unzip command doesn't seem to fully support split zip files yet. In my test, after doing a `cat` on the split zip files, even though there were such warnings, the content was successfully extracted. Zip4j generates the split zip file as per the zip specification, and this issue is a lack of support for split zip files in `unzip`, and there is nothing much that I can do.

**Comment by srikanth-lingala** [comment]
> what is the recommended way to unzip a split zip?

I would suggest using any other zip utility which supports split zip files. If you have to use command line for split zip file, I would suggest using 7z command line utility.

**Comment by yarix** [comment]
thanks.
`cat` was working for me as well, just wanted to be sure i don't miss anything.
