### ISSUE TITLE
I want to extract a folder from password protected zip file.

### ISSUE THREAD

**Issue by Dhruvkanani** [srikanth-lingala/zip4j#185]
I want to extract a folder from password protected zip file. I tries but it does't work. Need codes for this.

**Comment by srikanth-lingala** [comment]
It is at the moment not possible to extract a single folder from inside a zip file. This will be a good new feature to add, and I will include it in a future feature release. A workaround however, is to find out all the files inside that folder and call `ZipFile.extractFile()` for each of that file. You can find out the files in a directory by doing a `fileName.startsWith()`. For example, if your directory name that you want to extract is `root_dir/folder_to_extract/`, you have to compare this with all files in the directory and for each extract that file.

**Comment by srikanth-lingala** [comment]
I have added a feature so that if the file you want to extract is a directory, all the files under the directory in the zip will also be extract. In other words, to extract a single directory (with all its file and sub-folders), all you have to do now is: 

`ZipFile.extractFile("folder_name_to_extract\", "output_folder");`

I will include this feature in the next release.

**Comment by srikanth-lingala** [comment]
Feature added in v2.6.0 released today.
