### ISSUE TITLE
Split file issue

### ISSUE THREAD

**Issue by jeffreysmooth** [srikanth-lingala/zip4j#187]
When I tried to split just above 10MB zip (10267 KB) file into 5MB per file which created .z01, .z02 without .zip.
Each .z01,.z02 file has 5120 KB .

Code which I used:
```
ZipFile zipFile = new ZipFile(outputPath);

try {
       zipFile.createSplitZipFileFromFolder(new File(inputPath), new ZipParameters(), true, splitsize);
}
catch (ZipException e) {
      logger.error("Error while compressing files",e);
}
```

**Comment by srikanth-lingala** [comment]
As you are not able to provide the zip file (discussed via email), it will be quite hard to investigate this issue. I tried already to reproduce it with the sizes mentioned in your issues, but failed to reproduce it. To be honest, it will be difficult to reproduce just based on the size of the files because the end result size of the zip file will depend on a lot of other factors. 

Without the file to reproduce this issue, the only option left for me is to ask you a lot of questions in an attempt to reproduce this, so please bear with me:

- Does this issue happen with only the one file (the one with ~ 10MB) or does it happen with any other file as well.
- Which version of zip4j are you using?
- Is there any exception when your code is executed?
- Can you debug the code in the method `SplitOutputStream.startNextSplitFile()` and see if the zip file is created? Basically, every time a new split file is started, zip4j starts a ".zip" file and when a new split file has to start, it renames the current ".zip" part to ".z01" or ".z02", etc. Is there any exception during this method execution, especially on line 123 of this class. 
- Is there any chance that any other part of your code is deleting the zip file or something like that (renaming, etc)?
- Is the .zip file totally missing or is it a file with 0 length?
- To speed things up, will it be possible to agree on a time, and do attended testing?

To be honest, I am quite surprised that the .zip file is missing, because by default zip4j starts writing to a .zip file, and only when a new part is required, zip4j renames the current part being written to the appropriate part number (z01, z02, etc). It is hard to imagine that the .zip file is missing after the code execution.

**Comment by jeffreysmooth** [comment]
I have debugged the code which you have mentioned and noticed it is creating the file.I am deleting previously created file before calling compress method.However my delete operation deleting the output file.I am using spring batch and below are flow of my code.

Step1 : Deleting existing files  
    file.deleteOnExit();
Step2: Reading the input files
Step 3: Procesing files
step 4 :Writing files
Step 6: Compressing file

For further analysis, I found that  file.deleteOnExit(); setting hookup on the path and delete the files. So I have modified my code to use file.delete() that solved the issue.

Thanks for the support.

**Comment by jeffreysmooth** [comment]
Hi Srikanth,

I have debugged the code which you have mentioned and noticed it is
creating the file.
I am deleting previously created file before calling compress
method.However my delete operation deleting the output file.
I am using spring batch and below are flow of my code.

Step1 : Deleting existing files
    file.deleteOnExit();
Step2: Reading the input files
Step 3: Procesing files
step 4 :Writing files
Step 6: Compressing file

For further analysis, I found that  file.deleteOnExit(); setting hookup on
the path and delete the files.So I have modified my code to use
file.delete() that solved the issue.

Also I have closed the issue which I have opened.

Thanks for the support.

Thanks and regards,
Jeffrey
