### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by Godsbox** [srikanth-lingala/zip4j#21]
ZipFile zipFile = new ZipFile("filename.zip");
FileHeader fileHeader = zipFile.getFileHeader("entry_name_in_zip.txt");
InputStream inputStream = zipFile.getInputStream(fileHeader);

Here's the error message

2019-07-12 17:08:55.617 3397-3555/xxxxxxE/CrashHandler: In thread: Thread[TaskSchedulerFo,5,main]
    UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.lingala.zip4j.model.AbstractFileHeader.isDirectory()' on a null object reference
        at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:113)
        at org.chromium.android_webview.InputStreamUtil.read(Unknown Source)
2019-07-12 17:08:55.617 3397-3555/com.lzj.shanyi E/AndroidRuntime: FATAL EXCEPTION: TaskSchedulerFo
       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.lingala.zip4j.model.AbstractFileHeader.isDirectory()' on a null object reference
        at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:113)
        at org.chromium.android_webview.InputStreamUtil.read(Unknown Source)

**Comment by srikanth-lingala** [comment]
You get this error because you do not do a null check on `fileHeader`. Does the zip file contain the entry by name `entry_name_in_zip.txt`. Please note that the name here is with respect to the directory. That means, if you have the entry `entry_name_in_zip.txt` in a directory called `some_dir`, then the your code should be:

`FileHeader fileHeader = zipFile.getFileHeader("some_dir/entry_name_in_zip.txt");`

If fileHeader is null, this means that an entry by that name does not exist in the zip file.

If this is not the case, and if an entry by that name exists in the zip file (and also at the root directory), it would be great if you can attach the zip file. It makes it easier for me to investigate

**Comment by Godsbox** [comment]
![xxx](https://user-images.githubusercontent.com/15082011/61120211-058fb380-a4cf-11e9-8d4b-83371ca9562e.png)

I had a null check.

**Comment by srikanth-lingala** [comment]
Your exception says that localfileheader was null. 

> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.lingala.zip4j.model.AbstractFileHeader.isDirectory()' on a null object reference
> at net.lingala.zip4j.io.inputstream.ZipInputStream.read(ZipInputStream.java:113)

So, it still somehow got there even with a null check. So, obviously it was not this null check but the read method is being called somewhere else in your code. Can you please debug and see if the inputstream is being read from somewhere else? 

Unfortunately, it is hard for me to investigate further without more details. Would it be possible to extract it into a reproducible code and attached here (preferably along with the zip file)?
