### ISSUE TITLE
Jar is flagged as Java.Trojan.GenericGBA.27895

### ISSUE THREAD

**Issue by anypaddev** [srikanth-lingala/zip4j#232]
Hi, 

The release jar downloaded from maven repository is being flagged as Java.Trojan.GenericGBA.27895 in VirusTotal. Any idea about this? 

Regards.

**Comment by srikanth-lingala** [comment]
Thats extremely strange. Luckily VirusTotal website allows to upload a file to verify. I uploaded several versions of zip4j and noticed that it complains of this problem since v2.6.1 of zip4j. Some virus scanners are particularly sensitive to the way code executes. Especially with zip tools/programs, some virus scanners be particularly sensitive because of zip issues like these: [1][1], [2][2]. It might be the case the the antivirus tools upgraded their logic and this coincides the release v2.6.1 or it might be that some fix/new feature in v2.6.1 is being marked as suspicious by some of these tools. Whatever the case is, this is definitely a false positive. But I will check this.

[1]: https://en.wikipedia.org/wiki/Zip_bomb
[2]: http://www.aerasec.de/security/advisories/decompression-bomb-vulnerability.html

**Comment by srikanth-lingala** [comment]
The good thing about VirusTotal, as mentioned in my post above, is that it allows me to upload a file to verify the results. After a lot of uploads and scans by rolling back each commit of the changes involved in v2.6.1, I was able to pin point the commit which is causing this behaviour. And after some more experiments, I was even able to figure out the exact line and change which is causing this behaviour. 

[This][1] is the commit, and [this][2] is the line that is causing this behaviour. If I replace 

`currentSplitFileCounter = ((OutputStreamWithSplitZipSupport) outputStream).getCurrentSplitFileCounter();`

with 

`currentSplitFileCounter = ((CountingOutputStream) outputStream).getCurrentSplitFileCounter();`

(I just replaced `OutputStreamWithSplitZipSupport` with `CountingOutputStream`)

and generate the jar file (`mvn clean install -DskipTests`), and upload it to VirusTotal, and run a scan, all is fine. You can try this yourself as well. Just do the steps mentioned above, and VirusTotal does not complain anymore. This is obviously a false positive, and some bug or some wrong configuration in their virus definitions. I will see what I can do from my side. Maybe I can report this behaviour to VirusTotal if possible (which I am sure will ask me to contact those virus developers which is probably understandable), or maybe I can change some code in zip4j, which I do not really like because this is like changing my code because of issue with some virus tools. I will try to contact the virus tool developers.

[1]: https://github.com/srikanth-lingala/zip4j/commit/b2f8fa64d6a6b4da7dad5d3cdffd69a13053f3a4
[2]: https://github.com/srikanth-lingala/zip4j/commit/b2f8fa64d6a6b4da7dad5d3cdffd69a13053f3a4#diff-3b2846756d11a34f44ed292688f3a82eR355

**Comment by srikanth-lingala** [comment]
I have [reported the issue][1] on AdAware forums, and waiting for support from them.

[1]: https://forum.adaware.com/index.php?/topic/37752-false-positive-with-zip4j/

**Comment by srikanth-lingala** [comment]
It seems like the issue is fixed. I have reported the issue to Bitdefender and they seem to have fixed it. Only one tool, a Poland based Arcabit still reports this error, but they probably cache the defintions file and my best guess is that over time, this will go away as well. [Here][1] is the result of the build I just made and uploaded to VirusTotal. Please note that if you verify the same jar file which was scanned already earlier (like the jar from maven central), VirusTotal might still report the warnings, because they seem to cache the result based on the hash of the file. To avoid this, I generated the jar each time I wanted to verify. I will now mark this as resolved.

[1]: https://www.virustotal.com/gui/file/81b11a5e2ec122e4e8eb7a3769a5d2b815ff38705cec484ce9b60b9787bf3cac/detection

**Comment by srikanth-lingala** [comment]
Even the last remaining tool, Arcabit, [does not report][1] any issue anymore. Closing this issue.

[1]: https://www.virustotal.com/gui/file/81b11a5e2ec122e4e8eb7a3769a5d2b815ff38705cec484ce9b60b9787bf3cac/detection

**Comment by anypaddev** [comment]
Thank you!
