### ISSUE TITLE
about memory use?

### ISSUE THREAD

**Issue by 256655** [srikanth-lingala/zip4j#233]
is zip4j read all file size into memory ?

**Comment by 256655** [comment]
now I use shell command "zip -q -r test.zip test" ,by this way ,  I can save JVM memory use.   so I want to know is zip4j read all file into memory?

**Comment by srikanth-lingala** [comment]
If you are using `ZipFile` api, zip4j uses a buffer size of 4kb to read the content from zip file. Note however that this does not mean that zip4j memory usage is around 4kb. This will be a bit higher because of some additional calculations, some additional buffers that have to be maintained. But zip4j never reads the complete file into memory. (Of course, if the entry size is <= 4kb, then of course, it reads the complete file into memory). 

If you are using `ZipInputStream`, the buffer size is controlled by you.

**Comment by 256655** [comment]
my program run these steps:
1. some files already on disk
    like:
    test/a.xls
    test/b.xls ..
2. package these file into a zip file
    like:
    test.zip
cause these file very large，for save JVM memory，so i cannot read all these files into memory
so in this case, your zip4j can resolve this problem?

**Comment by srikanth-lingala** [comment]
As mentioned earlier, if you use ZipFile api, zip4j will not read the complete file into memory. It will read 4kb at a time. So you do not have to worry about zip4j reading complete file into memory if you .

**Comment by srikanth-lingala** [comment]
Closing this issue, as there is no further feedback.

**Comment by 256655** [comment]
thanks very much!
