### ISSUE TITLE
"java.io.EOFException: Unexpected end of input stream" when I unzip file

### ISSUE THREAD

**Issue by kdelarue** [srikanth-lingala/zip4j#262]
Hi, 

I'm triying to unzip a file which contains a lot of CSV files, extract failed with the error below :

![image](https://user-images.githubusercontent.com/14347443/100426770-b5000280-3091-11eb-97e9-99bb0becdbfb.png)

`11-27 09:06:21.367 16591-16836/fr.nerium.android.ND2.v10171600 W/System.err: net.lingala.zip4j.exception.ZipException: java.io.EOFException: Unexpected end of input stream
11-27 09:06:21.467 16591-16836/fr.nerium.android.ND2.v10171600 W/System.err:     at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:53)
11-27 09:06:21.467 16591-16836/fr.nerium.android.ND2.v10171600 W/System.err:     at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
11-27 09:06:21.477 16591-16836/fr.nerium.android.ND2.v10171600 W/System.err:     at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:436)

I repoduced this error only on older version of Android (5.1.1), with the same code version on an Android 8.1 device all is fine, unzip process is completed. 

When I manually modified the zip files and retry to unzip , unzip process is completed.

the zip which doesn't work is this :
[TabBBC1.zip](https://github.com/srikanth-lingala/zip4j/files/5606727/TabBBC1.zip)

Thanks for you're help

**Comment by srikanth-lingala** [comment]
The zip file was successfully extracted also on my mac. I guess this is an issue specific to older versions of zip4j. There might as well been  a bug in that version of Android which was fixed. I am not familiar with Android, and unfortunately do not have enough time to get myself familiar now for this issue as well, especially for something that could be a bug on Android, which probably was fixed in later versions of Android. Unfortunately, I will not be able to help here.
