### ISSUE TITLE
User FileHeader to get filename is random code

### ISSUE THREAD

**Issue by JohnJyong** [srikanth-lingala/zip4j#270]
When I zip the file in Mac os system, the filename is random code in fileHeader  .i have set the charset as UTF_8 and GBK, but it is still failure.
But in Windows system  it is fine .

**Comment by JohnJyong** [comment]
File storageFile = transformToFile(storageInputStream, fileName);
ZipFile zf = new ZipFile(storageFile);
zf.setCharset(Charset.forName("UTF-8"));
List<FileHeader> fileHeaders = zf.getFileHeaders();
for(int i = 0 ; i < fileHeaders.size() ; i++){
  FileHeader fileHeader = fileHeaders.get(i);
  String zipEntryName = fileHeader.getFileName();
}

**Comment by srikanth-lingala** [comment]
Would it be possible to attach a sample zip file which has this issue?

**Comment by srikanth-lingala** [comment]
Which version of zip4j are you using?

**Comment by srikanth-lingala** [comment]
I have tested this with the latest version of zip4j and it works fine. Note that you have to set the charset both during zip creation and extraction. Setting the charset only during extraction will not help. Try this with the latest version.  

Since there is no feedback for a long time on this issue, I am going to close it. Feel free to reopen if you still face this issue with the latest version.
