### ISSUE TITLE
ZipOutputStream as source for ZipInputStream makes CHECKSUM_MISMATCH

### ISSUE THREAD

**Issue by ludekz** [srikanth-lingala/zip4j#271]
I make byte array using ZipOutputStream.  Output works good in 7Zip, I can open in and unzip. When I try to use such output as input for ZipInputStream. I get exception CHECKSUM_MISMATCH.

```
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.apache.commons.io.IOUtils;


import net.lingala.zip4j.exception.ZipException;
import net.lingala.zip4j.io.inputstream.ZipInputStream;
import net.lingala.zip4j.io.outputstream.ZipOutputStream;
import net.lingala.zip4j.model.LocalFileHeader;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.CompressionMethod;
import net.lingala.zip4j.model.enums.EncryptionMethod;

class Scratch {

    public static void main(String[] args) {
        String sampleText = "sampleText";
         ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        try (ZipOutputStream zipOutputStream = new ZipOutputStream(byteArrayOutputStream)) {
            final ZipParameters zipParameters = buildZipParameters("simpleFile.txt");
            zipParameters.setEntrySize(1L); // just one file in the zip

            zipOutputStream.putNextEntry(zipParameters);
            IOUtils.write(sampleText, zipOutputStream, StandardCharsets.UTF_8);
            zipOutputStream.closeEntry();
        } catch (final IOException e) {
            System.err.println(e);
        }

        final ByteArrayInputStream inputStream = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());

        try (ZipInputStream zipInputStream = new ZipInputStream(inputStream)) {
            final LocalFileHeader localFileHeader = zipInputStream.getNextEntry();
            final String fileName = localFileHeader.getFileName();
            final String content = IOUtils.toString(zipInputStream, StandardCharsets.UTF_8);
            System.out.println(fileName + " " + content);
        } catch (ZipException zipException) {
            System.err.println(zipException.getType());
            System.err.println(zipException);
        } catch (final IOException e) {
            System.err.println(e);
        }
    }

    private static ZipParameters buildZipParameters(final String filename) {
        final ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionMethod(CompressionMethod.STORE);
        zipParameters.setEncryptionMethod(EncryptionMethod.NONE);
        zipParameters.setFileNameInZip(filename);
        return zipParameters;
    }
}

```

**Comment by srikanth-lingala** [comment]
Your code is almost right. Only one small change needed to get it working correctly. This:

`zipParameters.setEntrySize(1L);`

should be:

`zipParameters.setEntrySize(sampleText.length());`

Basically, the entry size is the uncompressed size (length) in bytes of the entry you are adding. In your case, since you are adding a string, it will be the length of the string.

**Comment by ludekz** [comment]
@srikanth-lingala 
Hello, thank for replay. 

I see where was problem.
Anyway, the wrongly created zip file was opened in 7zip and decompressed without problem. So for me it is confusing, that even if the file is OK, for 7zip, I get CHECKSUM_MISMATCH error from zip4j. 

I think such case should be handled more gracefully.

**Comment by srikanth-lingala** [comment]
> So for me it is confusing, that even if the file is OK, for 7zip, I get CHECKSUM_MISMATCH error from zip4j.

It depends on the way tools read content from zip file. Some tools read from central directory (central location of all entries in zip file), and some tools read from local entries (headers before the file entry). Zip4j uses a combination of both. If some tools extract it, this does not necessarily mean that those tools are more reliable, but as mentioned above, it just might be the case that those tools are reading from a different location. Better would be of course to fix the root cause of the problem, which in this case was to pass in the right size of the entry being added. This will make the zip file compatible with all the zip tools.
