### ISSUE TITLE
Tests do no pass under windows

### ISSUE THREAD

**Issue by Dunemaster** [srikanth-lingala/zip4j#291]
FileUtilsTest.testGetRelativeFileWithRootFolderNameInZip
FileUtilsTest.testGetRelativeFileWithDifferentFileNameInZipAndRootFolderNameAndDefaultFolderPath
FileUtilsTest.testGetRelativeFileWithRootFolderNameInZipWithFileSeparator
FileUtilsTest.testGetRelativeFileWithRootFolderNameInZipWithSeparatorsInName
FileUtilsTest.testGetRelativeFileWithDifferentFileNameInZipAndRootFolderName

org.junit.ComparisonFailure: 
Expected :"rootfolder\somefile.txt"
Actual   :"rootfolder/somefile.txt"

![image](https://user-images.githubusercontent.com/6681790/109425351-d6f28380-79f8-11eb-83db-3dd747697c83.png)

**Comment by IkoRein** [comment]
Hit this too just now. 

The reason it fails, is because e.g. on the 
testGetRelativeFileWithRootFolderNameInZip
the pathSeparator is set to FILE_SEPARATOR. Replacing it with ZIP_FILE_SEPARATOR in all those 5 failing test cases makes the tests pass. And the compiled package works on Windows. 

Cheers

**Comment by srikanth-lingala** [comment]
Issue fixed. [Commit](https://github.com/srikanth-lingala/zip4j/commit/9fe0987ed7071ff1aea3cd6e77ea6041f7ab42e1)

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.
