### ISSUE TITLE
Feature Request: ZipInputStream should properly implement `available()`

### ISSUE THREAD

**Issue by timofurrer** [srikanth-lingala/zip4j#311]
The https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/inputstream/ZipInputStream.java should properly implement the `InputStream::available()` method preferably with the same behavior as https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipInputStream.html#available()

In the meanwhile, do you have a workaround for that?

**Comment by srikanth-lingala** [comment]
When usiing ZipInputStream, it is unfortunately not possible to calculate the available bytes in the stream. It is because you have to read the complete zip file to know the exact available size which defeats the purpose of available. The reason you have to read through the complete file is you need to know the compressed sizes of each of the entry, and this information is stored in the headers which start before the entry itself. So, to know the number of bytes remaining in the stream, you need to first know the total amount of bytes you have in the stream, and this cannot be known, as explained above, unless you first read through the complete stream. It is for this purpose as well that JDK's ZipInputStream [either returns a 0 or a 1](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/util/zip/ZipInputStream.java#L154). I will probably also add something similar to zip4j's inputstream instead of returning 0 in each case.

**Comment by timofurrer** [comment]
Yes, I'm aware of that. That's why I suggested to implement the `0` or `1` byte return value in the first place ;)

**Comment by srikanth-lingala** [comment]
Oops. Sorry for that :-) I read the headline, and started thinking about a solution for it without reading your message completely. 

I will add your suggestion in the next release.

**Comment by timofurrer** [comment]
Amazing! Looking forward to it :tada:

**Comment by srikanth-lingala** [comment]
Feature added in v2.8.0 released today.
