### ISSUE TITLE
Is there a way to detect if a file within the zip is encrypted?

### ISSUE THREAD

**Issue by lakshans** [srikanth-lingala/zip4j#383]
I am using the ZipInputStream to process an encrypted Zip file. I need to then confirm if any of the files within the zip are encrypted. Is there a simple way to do this?

**Comment by srikanth-lingala** [comment]
With ZipInputStream, you have to read through the entries to determine if the file is encrypted. ZipFile api can read just the zip metadata to determine if any entry in a zip is encrypted. But since ZipInputStream cannot read the metadata, you have to read through all the entries, and break your loop if any of the entry is encrypted. Something like this should work:

```
try(ZipInputStream zipInputStream = new ZipInputStream(new FileInputStream("zipfile.zip"))) {
  LocalFileHeader localFileHeader;
  boolean atleastOneEntryInZipIsEncrypted = false;
  while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
    if (localFileHeader.isEncrypted()) {
      atleastOneEntryInZipIsEncrypted = true;
      break;
    }
  }
}
```
