### ISSUE TITLE
how to enable password for zip archive?

### ISSUE THREAD

**Issue by 3harish** [srikanth-lingala/zip4j#386]
Here we are able to add password to the inner files in zip. i need password authentication for the entire zip not the inner files

**Comment by srikanth-lingala** [comment]
The feature you mention is called [Zip Strong Encryption](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT#:~:text=7.0%20Strong%20Encryption%20Specification). This is PKWARE Proprietary Technology and needs a license from them to use.

**Comment by 3harish** [comment]
> The feature you mention is called [Zip Strong Encryption](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT#:~:text=7.0%20Strong%20Encryption%20Specification). This is PKWARE Proprietary Technology and needs a license from them to use.
 
Is there any other way to do it ? I need to create a zip file that containing some pdf files in java . and i need to enable password for the zip file to open and view list of files in the zip in some softwares like winrar,winzip etc and not for the inner files

**Comment by srikanth-lingala** [comment]
The only cross compliant approach, which is according to the zip file specification is the Zip Strong as I mentioned in my earlier post. But since that is patented, your options, especially if your zip file have to be used by other users and tools is limited. But if your zip files have to be used within your organisation, and if the people using the zip file also use the same software, then you can probably write a custom encryption software. You can first generate the zip file and then encrypt the complete zip file using any other file encryption mechanism.
