### ISSUE TITLE
APK related problems

### ISSUE THREAD

**Issue by KingMahmud** [srikanth-lingala/zip4j#394]
Hi Srikanth sir, first of all thank you very much for your amazing zip4j library. Its like a life saver to me. As you know, "apk" files are also a type of archive. So i was trying to use your library to delete/check specific directories.
But it didnt work.
Example : zip.getFileHeader("assets/")
Even if the apk contains the directory, zip4j would return null for this. While for real zip files, it works.

A workaround : 

Another problem i faced is while removing entire directories.
Example : zip.removeFile("res/")
It wont work as well incase of apk archives while working for zips.

A workaround : a for loop with HeaderUtils.getFileHeadersUnderDirectory(zip.getFileHeaders(),"res/") and zip.removeFile(header)

I am not sure if other issues occur with apk, because i still did not face.

Thanks in advance, looking for your reply.

Regards,
Mahmud

**Comment by srikanth-lingala** [comment]
Hi Mahmud, thanks for your positive feedback of zip4j. I will look into this issue and update the thread here.

**Comment by KingMahmud** [comment]
Thanks sir😊

**Comment by KingMahmud** [comment]
Hello!
I hope you are fine.
Almost a year passed, any solutions?

**Comment by srikanth-lingala** [comment]
The reason `zip.getFileHeader("assets/")` does not return a `FileHeader` is because as per zip specification, adding directory entries to a zip/apk format is optional but it is generally highly recommended. For example, if there is a file `b.txt` in a directory `a`, and when you add `a/b.txt` to the zip file, usually there are two entries added: one for the directory `a`, and the other for file `a/b.txt`. But as mentioned earlier, adding the directory `a` is optional but recommended. In the case of apk files it seems that directory entries are not added, and this is the reason searching for the directory entry returns null.

One work around, if you want to delete all the files under `/res` is for you is to explicitly search for entries starting with file name `res/` and delete all of them.

```
ZipFile zipFile = new ZipFile("sample.apk");
List<FileHeader> fileHeaders = zipFile.getFileHeaders();
for (FileHeader fileHeader : fileHeaders) {
  if (fileHeader.getFileName().startsWith("res/")) {
    zipFile.removeFile(fileHeader);
  }
}
```

**Comment by KingMahmud** [comment]
I see.
Thanks for the workaround.
