### ISSUE TITLE
ZipFile API methods return this

### ISSUE THREAD

**Issue by LeeYoung624** [srikanth-lingala/zip4j#40]
Hey @srikanth-lingala , I was looking for a zip library and I recently find zip4j. I think this is a great lib, the code is clear and is well documented. Great job!
I have some suggestions : would you consider returning `this` for the APIs in ZipFile? Here is my use case : I have some files and directories to be zipped, and I want them to be zipped in a single line of code like this : 
`new ZipFile("filename.zip").addFile("filename.ext").addFolder(new File("/user/myuser/folder_to_add"));`
I think the API methods returning `this` would work for this use case, and it would make the code more clear.

BTW, I like `zip4j` and I'd like to contribute to `zip4j`. Do you have any ideas about what I can do for `zip4j`? :)

**Comment by srikanth-lingala** [comment]
Thanks for your feedback. In general I like the idea of fluent API. The only point I have to think about is the implications of defining this. Because honestly speaking, this is a nice-to-have feature, and once we introduce this the return types of these methods are then fixed and final for all future API's. I just would like to think about that this will not block any other return types that might be more useful than any other return types. I will get update this thread again on this.

> I'd like to contribute to zip4j. Do you have any ideas about what I can do for zip4j? :)

I really appreciate that. I think you should first get familiar with the code and [zip specification][1]. You can skip the encryption logic for now (it can get overwhelming in the beginning). But dig deeper into the code and the specification. Please feel free to ask me any questions you have. I will try my best to assist you. If you want, you can also write me an email (my email is in README). 

[1]: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

**Comment by LeeYoung624** [comment]
Hey srikanth-lingala. Thank you for your replay :)
I'm reading the `zip4j` code recently, and I'm also learning about zip specification. I'm familiar with compression algorithms (LZ77, Huffman, Deflate, ANS, FSE) and I'm interested in all kinds of zip libraries. Do you have any plannings about new features for `zip4j`? I'd like to contribute to them.
