### ISSUE TITLE
Expose origin file name bytes for encoding issue

### ISSUE THREAD

**Issue by JJSimon17** [srikanth-lingala/zip4j#412]
Thanks for provide this awesome project. I notice that there are some entry file name encoding issues already, I also encounter one. I find below code in HeadReader. Would you like to expose the origin file name bytes to user? Add another file name bytes field to the LocalFileHeader, so we can handle the encoding issue in special situation.

```
if (fileNameLength > 0) {
  byte[] fileNameBuf = new byte[fileNameLength];
  readFully(inputStream, fileNameBuf);

  String fileName = decodeStringWithCharset(fileNameBuf, localFileHeader.isFileNameUTF8Encoded(), charset);
  localFileHeader.setFileName(fileName);
  localFileHeader.setDirectory(fileName.endsWith("/") || fileName.endsWith("\\"));
} else {
  localFileHeader.setFileName(null);
}
```

**Comment by srikanth-lingala** [comment]
This is a good point. I will consider this feature for the next release, if I see that there will be no side effects of this, which I don't think there should be, but just in case.

**Comment by JJSimon17** [comment]
Thanks for your feedback. The issue I face currently is that when I try to unzip files from network（thus I use ZipInputStream），I met zip entry name encoding issue，for chinese file entry names，sometimes use GBK for encoding，while sometimes use utf-8（and I found that the `fileNameUTF8Encoded` not always set for some zip files with utf-8 encoding），I'd like to use my own algorithm to detect the entry file name encoding.

**Comment by srikanth-lingala** [comment]
After lot of back and forth on wether to introduce this feature in zip4j, I decided not to do that, because, as mentioned in my earlier post, this will increase the memory footprint of zip4j. And to be honest, in all my years of supporting zip4j this is the first time I got such a request. 

However, what I can consider doing is to reload zip file metadata when you set charset so that if one charset does not work for you, you can change the charset which will reload the zip metadata with the new charset. It would be something like this:

```
ZipFile zipFile = new ZipFile("yourzip.zip");
zipFile.setCharset("UTF-8");

// read file metadata for example zipFile.getFileHeaders() and verify if the file name is as you expected
// If not
zipFile.setCharset("GBK");

// now read metadata again and verify your file name. Repeat until you reach the charset that works for you.

```

**Comment by JJSimon17** [comment]
Great，I think it's a better way that can also achieve my goal. Thanks.
