### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by TJHello** [srikanth-lingala/zip4j#42]
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at net.lingala.zip4j.headers.HeaderUtil.decodeStringWithCharset(HeaderUtil.java:67)
        at net.lingala.zip4j.headers.HeaderReader.readCentralDirectory(HeaderReader.java:196)
        at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:75)
        at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:831)
        at net.lingala.zip4j.ZipFile.isValidZipFile(ZipFile.java:791)

**Comment by LeeYoung624** [comment]
I'm not sure if you are having a `NoClassDefFoundError` or not. Detailed issue description is highly appreciated.
I believe you are coming across a error that you can't find class `java.nio.charset.StandardCharsets`. This's wired because it's included in `jdk` libraries. I'm using `JDK 1.8.0_191` and it's OK in my case. Maybe you can provide some detailed information, something like your operating system or the JDK version you're using.

**Comment by srikanth-lingala** [comment]
@TJHello Unfortunately, just the stack trace wont help us to investigate the issue. A bit more info would help to see if we can figure out any reason for this issue. All I can say for now is that this is a `NoClassDefFoundError` and not `ClassNotFoundException`.  `NoClassDefFoundError` occurs when there was any error in loading the class. This could be because of multiple same classes (from different libraries) in your classpath or because there was an error in loading this or any of it parent classes. You can look at your dependency tree and/or your logs to see if you see any exception related to this class.

**Comment by srikanth-lingala** [comment]
Closing this issue as there is no further feedback. Please reopen if you have any further info for us. Thanks.

**Comment by TJHello** [comment]
> 我不确定你是否有`NoClassDefFoundError`。详细的问题描述非常感谢。
> 我相信你遇到了一个你无法找到课程的错误`java.nio.charset.StandardCharsets`。这是有线的，因为它包含在`jdk`库中。我正在使用`JDK 1.8.0_191`，在我的情况下也没关系。也许您可以提供一些详细信息，例如您的操作系统或您正在使用的JDK版本。

这个问题出现在一些老旧的平板设备上。我相信就是JDK 1.8.0_191的问题，而如果用了低版本的JDK，就会导致这个问题。但其实你们在此处，可以使用别的方法来避免这个问题，从而兼容一些老设备。
目前，我使用了你们的1.3.2版本，可以解决该问题。

**Comment by srikanth-lingala** [comment]
@TJHello Please use English to discuss any issues you have. There is no way I can help you if you write in Chinese (I presume it is Chinese).

**Comment by LeeYoung624** [comment]
Well, maybe I can help you with some translation work. :)
I think @TJHello means that he met this error in a old version of zip4j, using an old version of JDK older than 1.8.0_191. Am I right? @TJHello
Therefore, I suggest you to provide some detail information, like the version of zip4j you are using when you met this error, and the JDK version you are using. I think this would help.

google translation
> 我认为@TJHello意味着他在旧版本的zip4j中遇到了这个错误，使用的是早于1.8.0_191的旧版JDK。 我对吗？@TJHello
因此，我建议您提供一些详细信息，例如您遇到此错误时使用的zip4j版本以及您正在使用的JDK版本。 我认为这会有所帮助

**Comment by TJHello** [comment]
This problem appears on some old tablet devices. I believe that is the problem with JDK 1.8.0_191. If you use a lower version of the JDK, this will cause this problem. But in fact, you can use other methods to avoid this problem, so it is compatible with some old devices.
Currently, I am using your version 1.3.2 to resolve this issue.

**Comment by TJHello** [comment]
（I thought that there are Google translations all over the world.）

**Comment by TJHello** [comment]
@srikanth-lingala
