### ISSUE TITLE
Unable to show progress while using Zipinputstream

### ISSUE THREAD

**Issue by rajgorantla9** [srikanth-lingala/zip4j#426]
Hi Srikanth,

First of all, thanks a lot for making such an awesome library for us. I have a few issues with the library which are listed below, hope you can help me. 

1. Unable to show progress while using Zipinputstream
2. Unable to find whether the zip is encrypted or not using Inputstream.

Please guide me if they are already there in the library.
waiting for your reply!

**Comment by srikanth-lingala** [comment]
> Unable to show progress while using Zipinputstream

This will unfortunately not possible, because with a stream, it is impossible to know the total size of the zip stream as the zip headers are located at the end of the zip stream. Without the total size of the archive, it will not be possible to determine the progress. If you want to show progress, the only option will be to use `ZipFile` api.

> Unable to find whether the zip is encrypted or not using Inputstream.

You can check that from the LocalFileHeader you get from `ZipInputStream.getNextHeader()`. `LocalFileHeader.isEncrypted()`
