### ISSUE TITLE
I'm using addStream method and passing ByteArrayInputStream as a argument but I want to append the data into single File. Currently it is overriding the old data which came from the inputStream.

### ISSUE THREAD

**Issue by malavmevada** [srikanth-lingala/zip4j#452]
`
   ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
        ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionLevel(CompressionLevel.ULTRA);
        zipParameters.setFileNameInZip(file.getName());
        new ZipFile(file + ".zip").addStream(byteArrayInputStream, zipParameters);
`

**Comment by srikanth-lingala** [comment]
This happens most likely because the filename that you set is the same each time. In this case zip4j replaces the content instead of adding new content. Can you make sure that the fileName being passed in this line `zipParameters.setFileNameInZip(file.getName())` is unique and does not already exist in the zip file?

**Comment by srikanth-lingala** [comment]
That won't be possible with zip4j. You have to first extract your file, then append your content to that file, and then add its content back to the zip file
