### ISSUE TITLE
ZipException: cannot delete old zip file

### ISSUE THREAD

**Issue by i0xHeX** [srikanth-lingala/zip4j#47]
Zip4J v2.1.2
JDK 11 (Oracle)
Windows 10

I'm getting the next error attempting to remove file from jar (zip) archive:
```
net.lingala.zip4j.exception.ZipException: cannot delete old zip file
	at net.lingala.zip4j.tasks.RemoveEntryFromZipFileTask.restoreFileName(RemoveEntryFromZipFileTask.java:171)
	at net.lingala.zip4j.tasks.RemoveEntryFromZipFileTask.cleanupFile(RemoveEntryFromZipFileTask.java:159)
	at net.lingala.zip4j.tasks.RemoveEntryFromZipFileTask.executeTask(RemoveEntryFromZipFileTask.java:70)
	at net.lingala.zip4j.tasks.RemoveEntryFromZipFileTask.executeTask(RemoveEntryFromZipFileTask.java:21)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:42)
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:36)
	at net.lingala.zip4j.ZipFile.removeFile(ZipFile.java:674)
	at net.lingala.zip4j.ZipFile.removeFile(ZipFile.java:650)
	at ua.i0xhex.signer.Signer.sign(Signer.java:101)
	at ua.i0xhex.signer.Signer.runMainApp(Signer.java:33)
	at ua.i0xhex.signer.Signer.main(Signer.java:26)
```

What's going in my code (simplified to zip operations only):
```
ZipFile zipFile = new ZipFile(file);
for (FileHeader header : (List<FileHeader>) zipFile.getFileHeaders()) {
	if (header.getFileName().equals("signature.txt")) {
		ZipInputStream stream = zipFile.getInputStream(header);
		data = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
		stream.close();
		break;
	}
}
zipFile.removeFile("signature.txt"); // 101 line here
```

Is this a bug or my fault? Anyway to fix this?

This error appears more often (up to 100%) on larger files, for example this didn't happened on 18 626 bytes archive, but happened on 8 364 918 bytes archive. For some archives it didn't happen from Nth time. Magic? I can send this archives privately if needed (it's not for public).

Also this error also appears on 1.3.3.

**Comment by srikanth-lingala** [comment]
Can you please let me know how you got the method `readAllBytes()` on `ZipInputStream`? This method is not defined in zip4j's `ZipInputStream`.

But more info related to this issue: When removing a file, zip4j will
1. create a temporary file in the same directory as the source zip file
2. copy all the content of the zip file except the file to be removed into the temporary zip file
3. delete the source zip file
4. rename the temporary zip file as the source zip filename

Your issue happens on step 3 because zip4j is unable to delete the source zip file. This is because there are other IO handles open on this file. Is there any other part of your code that is using this zip file? Another reason could be that there is not delete access on this folder, but since you say that sometimes it works, this is most likely not the case. We have tests in zip4j to make sure that the rename works, so the stream is being closed from zip4j. But if any other part of the code keeps a handle to this file open, then zip4j cannot delete it, and hence `removeFile` will not work. I highly suspect this might be the issue, but I also really wonder how you got the `readAllBytes()` from. If this is your custom implementation, please make sure that this part of the code is working fine, as this is not officially supported by zip4j.

**Comment by srikanth-lingala** [comment]
Closing the issue as there is no further feedback. Feel free to reopen if you have any further info and suspect there might be an issue in zip4j.

**Comment by i0xHeX** [comment]
I'm sorry for long response. 
The `readAllBytes()` method is a new method from `InputStream` appeared since Java 9 ([source](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/io/InputStream.java)).

Seems I solved my issue. The problem was in another zip file handler (hash computer) before removing `signature.txt`, which took stream of every file (except `signature.txt`) in archive and didn't close it after reading. But I'm still wondering how it worked before (with smaller archives).

Thank you for your help!
