### ISSUE TITLE
ZipInputStream.getNextEntry return only 1 entry, but next null

### ISSUE THREAD

**Issue by Kitsune2222** [srikanth-lingala/zip4j#49]
I'm use your library in Android app, and want extract/compress with Storage access framework, I see one way - streams, but ZipInputStream.getNextEntry in the second and next iteration return null, I'm try different zip archives, the same problem.
And second question, how with input stream get total files count and size before unpack (for progress bar) in zip?

**Comment by srikanth-lingala** [comment]
Make sure to read the content of the file before reading the next entry. Otherwise you will only get the first entry, as shown in the example below:

```
LocalFileHeader localFileHeader;
int readLen;
byte[] readBuffer = new byte[4096];

ZipInputStream zipInputStream = new ZipInputStream(new FileInputStream(new File(zipFile)));
while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
  // Make sure that you have the below while condition to read the entry completely
  // If you skip this while block, you will only get the first entry in the zip file
  while ((readLen = zipInputStream.read(readBuffer)) != -1) {
    
  }
}
```
If you still get only the first entry, please post the code you use and also the zip file.

> And second question, how with input stream get total files count and size before unpack (for progress bar) in zip?

With `ZipInputStream` you cannot get this information before hand. You need to use the `ZipFile` api for that. In a zip file structure, the number of files and sizes are stored at the end of the zip file. So it is not possible for `ZipInputStream` to support such feature.

**Comment by Kitsune2222** [comment]
Thank you for reply and library, with content reading all works.
