### ISSUE TITLE
Cannot unzip file created with zip4j

### ISSUE THREAD

**Issue by carikk** [srikanth-lingala/zip4j#494]
Hello, 

I'm using the version 2.11.5 of zip4j to create zip files with password. When i unzip them with 7zip it works, but when i use the commande line unzip i get the following error :
<img width="456" alt="Sans titre" src="https://user-images.githubusercontent.com/29362343/223790286-0efac04e-1d2e-4fd9-929a-1bda14c73d16.png">

We also tried to read it as stream from our ruby application but we get this error :
"General purpose flag Bit 3 is set so not possible to get proper info from local header"

Is there a way to fix this please ? or how can i disable data descriptor bit 3 ?

Thank you in advance.

**Comment by carikk** [comment]
Code Snippet : 
```
ZipParameters zipParameters = new ZipParameters();
zipParameters.setEncryptFiles(true);
zipParameters.setCompressionLevel(CompressionLevel.HIGHER);
zipParameters.setEncryptionMethod(EncryptionMethod.AES);
zipParameters.setFileNameInZip("contrats.json");

final File outputFileContracts = new File("contrats.json");

SequenceWriter sequenceWriter = mapper.writer()
    .withRootValueSeparator("\n")
    .writeValues(outputFileContracts);
    for (Contrat currentContrat : contratPAList) {
        sequenceWriter.write(currentContrat);
    }
sequenceWriter.close();
byte[] contractsFileContent = Files.readAllBytes(outputFileContracts.toPath());
ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(contractsFileContent);
ZipFile zipFile = new ZipFile(pathToZipFile, password.toCharArray());
zipFile.addStream(byteArrayInputStream, zipParameters);
```

Sample test file :
[Test.zip](https://github.com/srikanth-lingala/zip4j/files/10924226/Test.zip)

Password to unzip : testPassword

**Comment by srikanth-lingala** [comment]
There are two points here:

> When i unzip them with 7zip it works, but when i use the command line unzip i get the following error :

This is because unzip utility does not support `AES` encryption. If extracting via unzip is a must for you and you have to encrypt the zip file, your other option is to use `ZIP_STANDARD` encryption which I think is supported by unzip utility

> Is there a way to fix this please ? or how can i disable data descriptor bit 3 ?

zip4j creates a data descriptor when adding contents via stream. This has to be done because the size of the entries are not known upfront. If you have a file that you would like to add, adding it via `ZipFile.addFile()` method will not create a data descriptor.

**Comment by carikk** [comment]
This worked for me.
Thant you !
